export const ActionTypes = {
  DO_LOGIN_REQUEST: 'DO_LOGIN_REQUEST',
  DO_LOGIN_SUCCESS: 'DO_LOGIN_SUCCESS',

  DO_LOGIN_ERROR: 'DO_LOGIN_ERROR',

  DO_GET_LOGIN_REQUEST: 'DO_GET_LOGIN_REQUEST',
  DO_GET_LOGIN_SUCCESS: 'DO_GET_LOGIN_SUCCESS',

  DO_GETLOGIN_ERROR: 'DO_GET_LOGIN_ERROR',

  API_ERROR: 'API_ERROR',
  DO_USER_LOGOUT: 'DO_USER_LOGOUT',

  DO_OFFER_RIDE_REQUEST: 'DO_OFFER_RIDE_REQUEST',
  DO_OFFER_RIDE_SUCCESS: 'DO_OFFER_RIDE_SUCCESS',

  DO_BOOK_RIDE_REQUEST: 'DO_BOOK_RIDE_REQUEST',
  DO_BOOK_RIDE_SUCCESS: 'DO_BOOK_RIDE_SUCCESS',

  DO_GET_CARS_REQUEST: 'DO_GET_CARS_REQUEST',
  DO_GET_CARS_SUCCESS: 'DO_GET_CARS_SUCCESS',

  DO_GET_AVAILABLE_RIDES_REQUEST: 'DO_GET_AVAILABLE_RIDES_REQUEST',
  DO_GET_AVAILABLE_RIDES_SUCCESS: 'DO_GET_AVAILABLE_RIDES_SUCCESS',

  DO_PROFILE_REQUEST: 'DO_PROFILE_REQUEST',
  DO_PROFILE_SUCCESS: 'DO_PROFILE_SUCCESS',

  DO_DRIVER_PROFILE_SUCCESS: 'DO_DRIVER_PROFILE_SUCCESS',
  DO_DRIVER_PROFILE_REQUEST: 'DO_DRIVER_PROFILE_REQUEST',

  DO_ADD_CAR_SUCCESS: 'DO_ADD_CAR_SUCCESS',
  DO_ADD_CAR_REQUEST: 'DO_ADD_CAR_REQUEST',

  DO_GET_DRIVER_SUCCESS: 'DO_GET_DRIVER_SUCCESS',
  DO_GET_DRIVER_REQUEST: 'DO_GET_DRIVER_REQUEST',

  LIST_RIDE_SUCCESS: 'LIST_RIDE_SUCCESS',
  LIST_RIDE_REQUEST: 'LIST_RIDE_REQUEST',

  RATING_RIDE_SUCCESS: 'RATING_RIDE_SUCCESS',
  RATING_RIDE_REQUEST: 'RATING_RIDE_REQUEST',

  START_RIDE_SUCCESS: 'START_RIDE_SUCCESS',
  START_RIDE_REQUEST: 'START_RIDE_REQUEST',

  END_RIDE_SUCCESS: 'END_RIDE_SUCCESS',
  END_RIDE_REQUEST: 'END_RIDE_REQUEST',

  UPDATE_SCRATCH_SUCCESS: 'UPDATE_SCRATCH_SUCCESS',
  UPDATE_SCRATCH_REQUEST: 'UPDATE_SCRATCH_REQUEST',

  GET_REWARDS_SUCCESS: 'GET_REWARDS_SUCCESS',
  GET_REWARDS_REQUEST: 'GET_REWARDS_REQUEST'

};
